services:
  payload:
    image: ludogoriesoft/winetime-node:latest
    container_name: winetime-node
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: winetime-mongo
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  mongo-data:
  data:
  node_modules:
