/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export type CartItems = {
  product?: string | Product;
  quantity?: number;
  id?: string;
}[];
export type FavouriteItems = {
  product?: string | Product;
  id?: string;
}[];
export type Email = {
  Email?: string;
  id?: string;
}[];

export interface Config {
  collections: {
    products: Product;
    orders: Order;
    requests: Request;
    categories: Category;
    spirts: Spirt;
    otherCategories: OtherCategory;
    brands: Brand;
    'glass-types': GlassType;
    sorts: Sort;
    regions: Region;
    foods: Food;
    tags: Tag;
    blog: Blog;
    media: Media;
    pages: Page;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    settings: Settings;
    header: Header;
    footer: Footer;
  };
}
export interface Product {
  id: string;
  productType: 'wine' | 'otherBeverage' | 'other';
  title: string;
  price: number;
  discountPrice?: number;
  barcode: number;
  richText?: {
    [k: string]: unknown;
  }[];
  layout?: (
    | {
        invertBackground?: boolean;
        richText?: {
          [k: string]: unknown;
        }[];
        links?: {
          link: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              relationTo: 'pages';
              value: string | Page;
            };
            url: string;
            label: string;
            icon?: string | Media;
            appearance?: 'primary' | 'secondary';
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        invertBackground?: boolean;
        columns?: {
          size?: 'oneThird' | 'half' | 'twoThirds' | 'full';
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              relationTo: 'pages';
              value: string | Page;
            };
            url: string;
            label: string;
            icon?: string | Media;
            appearance?: 'default' | 'primary' | 'secondary';
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        invertBackground?: boolean;
        position?: 'default' | 'fullscreen';
        media: string | Media;
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
    | {
        introContent?: {
          [k: string]: unknown;
        }[];
        populateBy?: 'collection' | 'selection';
        relationTo?: 'products';
        categories?: string[] | Category[];
        brands?: string[] | Brand[];
        sorts?: string[] | Sort[];
        regions?: string[] | Region[];
        foods?: string[] | Food[];
        spirts?: string[] | Spirt[];
        tags?: string[] | Tag[];
        otherCategories?: string[] | OtherCategory[];
        limit?: number;
        selectedDocs?:
          | {
              relationTo: 'products';
              value: string;
            }[]
          | {
              relationTo: 'products';
              value: Product;
            }[];
        populatedDocs?:
          | {
              relationTo: 'products';
              value: string;
            }[]
          | {
              relationTo: 'products';
              value: Product;
            }[];
        populatedDocsTotal?: number;
        showOnlyDiscountedProducts?: boolean;
        showOnlyOtherProducts?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'archive';
      }
  )[];
  stripeProductID?: string;
  priceJSON?: string;
  enablePaywall?: boolean;
  paywall?: (
    | {
        invertBackground?: boolean;
        richText?: {
          [k: string]: unknown;
        }[];
        links?: {
          link: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              relationTo: 'pages';
              value: string | Page;
            };
            url: string;
            label: string;
            icon?: string | Media;
            appearance?: 'primary' | 'secondary';
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        invertBackground?: boolean;
        columns?: {
          size?: 'oneThird' | 'half' | 'twoThirds' | 'full';
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              relationTo: 'pages';
              value: string | Page;
            };
            url: string;
            label: string;
            icon?: string | Media;
            appearance?: 'default' | 'primary' | 'secondary';
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        invertBackground?: boolean;
        position?: 'default' | 'fullscreen';
        media: string | Media;
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
    | {
        introContent?: {
          [k: string]: unknown;
        }[];
        populateBy?: 'collection' | 'selection';
        relationTo?: 'products';
        categories?: string[] | Category[];
        brands?: string[] | Brand[];
        sorts?: string[] | Sort[];
        regions?: string[] | Region[];
        foods?: string[] | Food[];
        spirts?: string[] | Spirt[];
        tags?: string[] | Tag[];
        otherCategories?: string[] | OtherCategory[];
        limit?: number;
        selectedDocs?:
          | {
              relationTo: 'products';
              value: string;
            }[]
          | {
              relationTo: 'products';
              value: Product;
            }[];
        populatedDocs?:
          | {
              relationTo: 'products';
              value: string;
            }[]
          | {
              relationTo: 'products';
              value: Product;
            }[];
        populatedDocsTotal?: number;
        showOnlyDiscountedProducts?: boolean;
        showOnlyOtherProducts?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'archive';
      }
  )[];
  quantity?: number;
  weight?: number;
  categories: string | Category;
  spirts: string | Spirt;
  otherCategories: string | OtherCategory;
  brands?: string | Brand;
  glassTypes?: string | GlassType;
  sorts?: string[] | Sort[];
  regions?: string[] | Region[];
  foods?: string[] | Food[];
  visible?: boolean;
  publishedOn?: string;
  slug?: string;
  skipSync?: boolean;
  milliliters?: '50' | '250' | '330' | '375' | '500' | '700' | '750' | '1l' | '15l';
  alchoholPercentage?: number;
  isBio?: boolean;
  isHomemade?: boolean;
  isChosen?: boolean;
  isPrestige?: boolean;
  tags?: string[] | Tag[];
  wineClass?: 'igt' | 'doc' | 'docg' | 'dop' | 'aoc' | 'igp';
  wineColor?: string;
  wineAroma?: string;
  wineTaste?: string;
  wineTemperature?: string;
  relatedProducts?: string[] | Product[];
  media?: {
    upload?: string | Media;
    id?: string;
  }[];
  yanakName?: string;
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Page {
  id: string;
  title: string;
  publishedOn?: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'customHero';
    richText?: {
      [k: string]: unknown;
    }[];
    relationTo?: 'products' | 'bio';
    categories?: string[] | Category[];
    brands?: string[] | Brand[];
    sorts?: string[] | Sort[];
    regions?: string[] | Region[];
    foods?: string[] | Food[];
    spirts?: string[] | Spirt[];
    tags?: string[] | Tag[];
    links?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference: {
          relationTo: 'pages';
          value: string | Page;
        };
        url: string;
        label: string;
        icon?: string | Media;
        appearance?: 'default' | 'primary' | 'secondary';
      };
      id?: string;
    }[];
    media: string | Media;
  };
  layout: (
    | {
        invertBackground?: boolean;
        richText?: {
          [k: string]: unknown;
        }[];
        links?: {
          link: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              relationTo: 'pages';
              value: string | Page;
            };
            url: string;
            label: string;
            icon?: string | Media;
            appearance?: 'primary' | 'secondary';
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        invertBackground?: boolean;
        columns?: {
          size?: 'oneThird' | 'half' | 'twoThirds' | 'full';
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          link?: {
            type?: 'reference' | 'custom';
            newTab?: boolean;
            reference: {
              relationTo: 'pages';
              value: string | Page;
            };
            url: string;
            label: string;
            icon?: string | Media;
            appearance?: 'default' | 'primary' | 'secondary';
          };
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        invertBackground?: boolean;
        position?: 'default' | 'fullscreen';
        media: string | Media;
        id?: string;
        blockName?: string;
        blockType: 'mediaBlock';
      }
    | {
        introContent?: {
          [k: string]: unknown;
        }[];
        populateBy?: 'collection' | 'selection';
        relationTo?: 'products';
        categories?: string[] | Category[];
        brands?: string[] | Brand[];
        sorts?: string[] | Sort[];
        regions?: string[] | Region[];
        foods?: string[] | Food[];
        spirts?: string[] | Spirt[];
        tags?: string[] | Tag[];
        otherCategories?: string[] | OtherCategory[];
        limit?: number;
        selectedDocs?:
          | {
              relationTo: 'products';
              value: string;
            }[]
          | {
              relationTo: 'products';
              value: Product;
            }[];
        populatedDocs?:
          | {
              relationTo: 'products';
              value: string;
            }[]
          | {
              relationTo: 'products';
              value: Product;
            }[];
        populatedDocsTotal?: number;
        showOnlyDiscountedProducts?: boolean;
        showOnlyOtherProducts?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'archive';
      }
    | {
        name?: string;
        media?: string | Media;
        reverse?: boolean;
        firstCarousel: {
          populateBy?: 'collection' | 'selection';
          relationTo?: 'products';
          categories?: string[] | Category[];
          brands?: string[] | Brand[];
          sorts?: string[] | Sort[];
          regions?: string[] | Region[];
          foods?: string[] | Food[];
          spirts?: string[] | Spirt[];
          tags?: string[] | Tag[];
          limit?: number;
          priceOver?: number;
          priceLimit?: number;
          selectedDocs?:
            | {
                relationTo: 'products';
                value: string;
              }[]
            | {
                relationTo: 'products';
                value: Product;
              }[];
          populatedDocs?:
            | {
                relationTo: 'products';
                value: string;
              }[]
            | {
                relationTo: 'products';
                value: Product;
              }[];
          populatedDocsTotal?: number;
          showOnlyDiscountedProducts?: boolean;
          showOnlyOtherProducts?: boolean;
          quantityOverZero?: boolean;
        };
        secondCarousel: {
          populateBy?: 'collection' | 'selection';
          relationTo?: 'products';
          categories?: string[] | Category[];
          brands?: string[] | Brand[];
          sorts?: string[] | Sort[];
          regions?: string[] | Region[];
          foods?: string[] | Food[];
          spirts?: string[] | Spirt[];
          tags?: string[] | Tag[];
          limit?: number;
          priceOver?: number;
          priceLimit?: number;
          selectedDocs?:
            | {
                relationTo: 'products';
                value: string;
              }[]
            | {
                relationTo: 'products';
                value: Product;
              }[];
          populatedDocs?:
            | {
                relationTo: 'products';
                value: string;
              }[]
            | {
                relationTo: 'products';
                value: Product;
              }[];
          populatedDocsTotal?: number;
          showOnlyDiscountedProducts?: boolean;
          showOnlyOtherProducts?: boolean;
          quantityOverZero?: boolean;
        };
        id?: string;
        blockName?: string;
        blockType: 'twoRowCarousel';
      }
    | {
        selectedDoc?: {
          relationTo: 'products';
          value: string | Product;
        };
        reverse?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'bannerProduct';
      }
    | {
        card1: {
          media?: string | Media;
          cardTitle?: string;
          cardSubTitle?: string;
          relationTo?: 'products' | 'bio';
          categories?: string[] | Category[];
          brands?: string[] | Brand[];
          sorts?: string[] | Sort[];
          regions?: string[] | Region[];
          foods?: string[] | Food[];
          spirts?: string[] | Spirt[];
          tags?: string[] | Tag[];
        };
        card2: {
          media?: string | Media;
          cardTitle?: string;
          cardSubTitle?: string;
          relationTo?: 'products' | 'bio';
          categories?: string[] | Category[];
          brands?: string[] | Brand[];
          sorts?: string[] | Sort[];
          regions?: string[] | Region[];
          foods?: string[] | Food[];
          spirts?: string[] | Spirt[];
          tags?: string[] | Tag[];
        };
        card3: {
          media?: string | Media;
          cardTitle?: string;
          cardSubTitle?: string;
          relationTo?: 'products' | 'bio';
          categories?: string[] | Category[];
          brands?: string[] | Brand[];
          sorts?: string[] | Sort[];
          regions?: string[] | Region[];
          foods?: string[] | Food[];
          spirts?: string[] | Spirt[];
          tags?: string[] | Tag[];
        };
        card4: {
          media?: string | Media;
          cardTitle?: string;
          cardSubTitle?: string;
          relationTo?: 'products' | 'bio';
          categories?: string[] | Category[];
          brands?: string[] | Brand[];
          sorts?: string[] | Sort[];
          regions?: string[] | Region[];
          foods?: string[] | Food[];
          spirts?: string[] | Spirt[];
          tags?: string[] | Tag[];
        };
        card5: {
          media?: string | Media;
          cardTitle?: string;
          cardSubTitle?: string;
          relationTo?: 'products' | 'bio';
          categories?: string[] | Category[];
          brands?: string[] | Brand[];
          sorts?: string[] | Sort[];
          regions?: string[] | Region[];
          foods?: string[] | Food[];
          spirts?: string[] | Spirt[];
          tags?: string[] | Tag[];
        };
        id?: string;
        blockName?: string;
        blockType: 'wobbleCards';
      }
    | {
        media?: string | Media;
        richText?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'promotionBlock';
      }
  )[];
  slug?: string;
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Category {
  id: string;
  title: string;
  media?: string | Media;
  parent?: string | Category;
  breadcrumbs?: {
    doc?: string | Category;
    url?: string;
    label?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  caption?: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Brand {
  id: string;
  title: string;
  media?: string | Media;
  richText?: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Sort {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
export interface Region {
  id: string;
  title: string;
  otherRegion?: boolean;
  media?: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface Food {
  id: string;
  title: string;
  media?: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface Spirt {
  id: string;
  title: string;
  media?: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface Tag {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
export interface OtherCategory {
  id: string;
  title: string;
  media?: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface GlassType {
  id: string;
  title: string;
  media?: string | Media;
  richText?: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Order {
  id: string;
  status?: 'new' | 'processing' | 'sent' | 'finished';
  quickOrder?: boolean;
  name: string;
  orderedBy?: string | User;
  stripePaymentIntentID?: string;
  phone: number;
  email: string;
  total: number;
  deliveryMethod: 'econtOffice' | 'econtAddress' | 'quickOrder';
  placeOfResident: string;
  ekontOffice: string;
  addressNeighborhood?: string;
  addressStreet: string;
  items?: {
    product: string | Product;
    price?: number;
    quantity?: number;
    id?: string;
  }[];
  parcelAmount?: string;
  shipmentNumber?: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  name?: string;
  phone?: string;
  roles?: ('admin' | 'customer')[];
  purchases?: string[] | Product[];
  stripeCustomerID?: string;
  cart?: {
    items?: CartItems;
  };
  favourites?: {
    items?: FavouriteItems;
  };
  skipSync?: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password: string;
}
export interface Request {
  id: string;
  name: string;
  email: string;
  wineName: string;
  wineQuantity: number;
  addMore?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Blog {
  id: string;
  title: string;
  richText?: {
    [k: string]: unknown;
  }[];
  publishedOn?: string;
  slug?: string;
  skipSync?: boolean;
  relatedProductsText?: string;
  relatedProducts?: string[] | Product[];
  media?: {
    upload?: string | Media;
    id?: string;
  }[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string;
  batch?: number;
  updatedAt: string;
  createdAt: string;
}
export interface Settings {
  id: string;
  indexPage?: string | Page;
  newOrderEmails?: Email;
  requestProductEmails?: Email;
  contactUsFormEmails?: Email;
  productsPage?: string | Page;
  updatedAt?: string;
  createdAt?: string;
}
export interface Header {
  id: string;
  promotionBanner?: string;
  navItems?: {
    link: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference: {
        relationTo: 'pages';
        value: string | Page;
      };
      url: string;
      label: string;
      icon?: string | Media;
    };
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
export interface Footer {
  id: string;
  copyright: string;
  phone: string;
  navItems?: {
    link: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference: {
        relationTo: 'pages';
        value: string | Page;
      };
      url: string;
      label: string;
      icon?: string | Media;
    };
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}